### ISSUE TITLE
Plugin constructor() can't be launch

### ISSUE THREAD

**Issue by jugandomiguel** [rauenzi/BDPluginLibrary#200] opened 2023-05-31 10:26 UTC
![image](https://github.com/rauenzi/BDPluginLibrary/assets/73621705/18e61d47-6202-4b15-8f5c-ae007ad01e42)
TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://discord.com/assets/bda0a743ee0700462262.js:1779:54)
    at gu (https://discord.com/assets/bda0a743ee0700462262.js:1833:146)
    at Ic (https://discord.com/assets/bda0a743ee0700462262.js:1826:89)
    at mc (https://discord.com/assets/bda0a743ee0700462262.js:1826:17)
    at hc (https://discord.com/assets/bda0a743ee0700462262.js:1825:867)
    at uc (https://discord.com/assets/bda0a743ee0700462262.js:1822:983)
    at Fi (https://discord.com/assets/bda0a743ee0700462262.js:1762:577)
    at lc (https://discord.com/assets/bda0a743ee0700462262.js:1823:498)
    at https://discord.com/assets/bda0a743ee0700462262.js:1842:522
    at el (https://discord.com/assets/bda0a743ee0700462262.js:1842:561)
    at t.render (https://discord.com/assets/bda0a743ee0700462262.js:1846:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5617)

**Comment by Salty-Coder** [comment] 2023-05-31 10:29
Duplicate of #193.

**Closed** 2023-05-31 11:01 UTC
