### ISSUE TITLE
An error was encountered while trying to load this plugin. Still in need of a fix please.

### ISSUE THREAD

**Issue by joebison** [rauenzi/BDPluginLibrary#212] opened 2023-10-26 20:04 UTC
hello. Betterdiscord recently got updated and it mentions that certain plugins need to be updated to be fixed. I am aware that discord broke plugins and was hoping the latest update from Betterdiscord would fix this one. 
![Screenshot 2023-10-26 140151](https://github.com/rauenzi/BDPluginLibrary/assets/83432574/fe2cf6fa-daab-4f26-8711-1fe3c38e0f0f)
![Screenshot 2023-10-26 140139](https://github.com/rauenzi/BDPluginLibrary/assets/83432574/18ef2905-e0b5-40b8-bf78-8c206385c345)

**Comment by rauenzi** [comment] 2023-10-26 20:09
Yet another another duplicate of #207

**Closed by rauenzi** 2023-10-26 20:09 UTC

**Comment by joebison** [comment] 2023-10-27 04:54
so to better understand the problem with the plugin, its on Betterdiscord end to make the plugin work again? there has been 2 subsequent updates to it and the plugin still is non functional. thanks for the help. 

    On Thursday, October 26, 2023 at 02:10:00 p.m. MDT, Zerebos ***@***.***> wrote:  
 
 


Closed #212 as not planned.
