### ISSUE TITLE
ColorPicker settings disappear when hovered.

### ISSUE THREAD

**Issue by Arashiryuu** [rauenzi/BDPluginLibrary#10] opened 2019-05-22 20:11 UTC
I believe this is a tooltip error, it occurs whenever the default / display color is hovered or the color picker itself is hovered.

![zereslibColorPickerError](https://user-images.githubusercontent.com/24483230/58205261-0e85b500-7cd6-11e9-98e5-2d6f8302dd31.png)

**Comment by rauenzi** [comment] 2019-09-22 18:56
Seems like it no longer disappears, but it just straight up does nothing so... progress?

**Comment by rauenzi** [comment] 2019-09-27 17:21
After a lot more digging, I found the reason this is still breaking is the same reason the tooltips generally don't work--they aren't in the same react structure. Discord's tooltips for whatever reason do some internal checking to see if they're part of the structure in order to append them which is madness honestly. The two big blocks of the color picker have tooltips so that is why hovering either one of those causes it. So one thing you can do (for now) is when a color is needed to use a modal and push it onto discord's modal stack with the color picker in it, that way it is still a part of their react chain. Could also use native color input type, but that is less pretty. In the future with BBD, we will be able to just return a react component and it will all be in the same tree so it should be fixed with that.

**Comment by rauenzi** [comment] 2020-01-07 14:56
Is this still happening?

**Comment by Arashiryuu** [comment] 2020-01-15 17:40
Kind of? Now when I try to access a plugin's settings panel that's using the ColorPicker such as my ChatUserIDsRedux, it refuses to generate the panel and gives me an error.

![ColorPickerErrorNew](https://user-images.githubusercontent.com/24483230/72457238-10007200-37be-11ea-9468-44d80e2aff0e.png)

**Comment by rauenzi** [comment] 2020-03-07 01:06
The root cause here still seems to be the same, it doesn't like not being in the same react tree as Discord... I am trying to work around it. However there are still other options we could take:

- Make BBD accept react components so everything is in the same tree
- Create a custom color picker
- Use a styled version of `<input type="color">`

Thoughts?

**Comment by rauenzi** [comment] 2020-03-23 17:47
@Arashiryuu I went with
> Use a styled version of `<input type="color">`
for now so we can at least have color pickers.

**Comment by rauenzi** [comment] 2020-07-28 16:03
@Arashiryuu this should be fixed at latest level as long as the user has loaded the color picker in (by visiting roles settings or something similar)

**Closed** 2020-09-23 19:22 UTC
