### ISSUE TITLE
Addon Errors

### ISSUE THREAD

**Issue by Kuroo2021** [rauenzi/BDPluginLibrary#235] opened 2024-08-20 14:04 UTC
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.1354e847b849e32f30b1.js:12:5577573
    at l (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:9526809)
    at c (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:9527196)
    at l (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:5577547)
    at p (https://discord.com/assets/4faedc7004d68ac46077.js:1:6033)
    at aA (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:990088)
    at l (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1045324)
    at ok (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1028319)
    at https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1028185
    at oG (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1028193)
    at oD (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1025278)
    at r5 (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:973952)
    at ob (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1025782)
    at https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1053869
    at ll (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1053899)
    at t.render (https://discord.com/assets/web.1354e847b849e32f30b1.js:12:1057594)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by Technetium1** [comment] 2024-08-20 16:48
Duplicate of https://github.com/rauenzi/BDPluginLibrary/issues/231, please close this.

**Closed** 2024-08-20 17:52 UTC
