### ISSUE TITLE
An error was encountered while trying to load this plugin.(Again)

### ISSUE THREAD

**Issue by Peak20112** [rauenzi/BDPluginLibrary#210] opened 2023-10-25 16:43 UTC
![image](https://github.com/rauenzi/BDPluginLibrary/assets/101064515/f4e5457e-9284-4783-8799-83372bb3fa84)
I installed discord stable and it gave me this error

**Comment by rauenzi** [comment] 2023-10-25 16:45
Yet another duplicate of #207

**Closed by rauenzi** 2023-10-25 16:45 UTC
