### ISSUE TITLE
"Plugin Construcor() Could Not Be Fired"

### ISSUE THREAD

**Issue by Fishylizard1** [rauenzi/BDPluginLibrary#197] opened 2023-05-31 05:02 UTC
TypeError: Cannot read properties of undefined (reading 'Provider')
    at DiscordProviders (betterdiscord://plugins/0PluginLibrary.plugin.js:4674:41)
    at Sa (https://discord.com/assets/bda0a743ee0700462262.js:1779:54)
    at gu (https://discord.com/assets/bda0a743ee0700462262.js:1833:146)
    at Ic (https://discord.com/assets/bda0a743ee0700462262.js:1826:89)
    at mc (https://discord.com/assets/bda0a743ee0700462262.js:1826:17)
    at hc (https://discord.com/assets/bda0a743ee0700462262.js:1825:867)
    at uc (https://discord.com/assets/bda0a743ee0700462262.js:1822:983)
    at Fi (https://discord.com/assets/bda0a743ee0700462262.js:1762:577)
    at lc (https://discord.com/assets/bda0a743ee0700462262.js:1823:498)
    at https://discord.com/assets/bda0a743ee0700462262.js:1842:522
    at el (https://discord.com/assets/bda0a743ee0700462262.js:1842:561)
    at t.render (https://discord.com/assets/bda0a743ee0700462262.js:1846:205)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4584:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6238:49)
    at A.initializeAddon (betterdiscord/renderer.js:4:33541)
    at A.loadAddon (betterdiscord/renderer.js:4:7808)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5617)
    
    
    
![image](https://github.com/rauenzi/BDPluginLibrary/assets/107359118/fbe12d18-79df-4b91-a00c-c87358f82985)

**Comment by ann4belle** [comment] 2023-05-31 09:22
Possible dupe of #193

**Closed** 2023-05-31 15:26 UTC
