### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by Eivorr** [rauenzi/BDPluginLibrary#211] opened 2023-10-25 16:46 UTC
![image](https://github.com/rauenzi/BDPluginLibrary/assets/113300060/e5bb6c0e-7931-4abe-b601-9ded2211fc17)
yeah pretty much that, even tho themes arent working on betterdiscord either so i dont think its because of the plugin.

**Comment by rauenzi** [comment] 2023-10-25 16:47
Another duplicate of #207

**Closed by rauenzi** 2023-10-25 16:47 UTC
