### ISSUE TITLE
An error was encountered while trying to load this plugin

### ISSUE THREAD

**Issue by b1k3rdude** [rauenzi/BDPluginLibrary#231] opened 2024-08-15 07:23 UTC
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598937
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9600911)
    at c (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9601298)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598911)
    at p (https://discord.com/assets/8cd0ebdf4d0e19d304ee.js:1:5901)
    at aA (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:990633)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1045869)
    at ok (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028864)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028730
    at oG (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028738)
    at oD (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1025823)
    at r5 (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:974497)
    at ob (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1026327)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054414
    at ll (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054444)
    at t.render (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
![Untitled](https://github.com/user-attachments/assets/85ca3051-61ce-4641-a3e2-7da1f655441d)

**Comment by Matt7983** [comment] 2024-08-15 07:56
Same here.  Triggered the same error on this line:
`at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)`

Seems not the same issue with this
https://github.com/rauenzi/BDPluginLibrary/issues/224

**Comment by ElPediatra** [comment] 2024-08-15 14:34
Same...

```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598937
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9600911)
    at c (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9601298)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598911)
    at p (https://discord.com/assets/8cd0ebdf4d0e19d304ee.js:1:5901)
    at aA (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:990633)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1045869)
    at ok (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028864)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028730
    at oG (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028738)
    at oD (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1025823)
    at r5 (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:974497)
    at ob (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1026327)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054414
    at ll (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054444)
    at t.render (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

**Comment by cxosa** [comment] 2024-08-15 15:49
mine does this exact same thing but different.. happened this morning but it was working just fine last night


TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598937
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9600911)
    at c (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:9601298)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:5598911)
    at p (https://discord.com/assets/8cd0ebdf4d0e19d304ee.js:1:5901)
    at aA (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:990633)
    at l (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1045869)
    at ok (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028864)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028730
    at oG (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1028738)
    at oD (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1025823)
    at r5 (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:974497)
    at ob (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1026327)
    at https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054414
    at ll (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1054444)
    at t.render (https://discord.com/assets/web.fbc721351be4d1055a8c.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201

**Comment by StonebanksYT** [comment] 2024-08-15 16:53
Same..any fix?

**Comment by cxosa** [comment] 2024-08-15 16:54
nawl cuz, i been trying all morning

**Comment by ColonelGerdauf** [comment] 2024-08-15 16:58
I have been struggling to find the cited lines, as they are in empty spaces on GItHub. The closest I could find was the following:
`ui__WEBPACK_IMPORTED_MODULE_1__.Popouts.initialize();`

I do not know yet what that is referencing or what the chain of operation is.

**Comment by Zhurama** [comment] 2024-08-15 18:21
I have the same error as well.. Namaste.

**Comment by AtomicTEM** [comment] 2024-08-15 18:27
Same

**Comment by h4skell** [comment] 2024-08-15 18:28
same error

**Comment by angrybirdice** [comment] 2024-08-15 18:45
same

**Comment by tgrafk12** [comment] 2024-08-15 22:42
getting the same error. made another plugin that tried to load, crash discord entirely. eh. 
would help if i knew the plugin better, but figured id mention its broken for me too.

```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576698
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523341)
    at c (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523728)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576672)
    at p (https://discord.com/assets/958ef280f246c8d801de.js:1:5901)
    at aA (https://discord.com/assets/web.afed570d83e54e09da87.js:12:990633)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1045869)
    at ok (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028864)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028730
    at oG (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028738)
    at oD (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1025823)
    at r5 (https://discord.com/assets/web.afed570d83e54e09da87.js:12:974497)
    at ob (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1026327)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054414
    at ll (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054444)
    at t.render (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by B-Nerd** [comment] 2024-08-15 22:51
zeres plugin libraty error
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576698
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523341)
    at c (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523728)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576672)
    at p (https://discord.com/assets/958ef280f246c8d801de.js:1:5901)
    at aA (https://discord.com/assets/web.afed570d83e54e09da87.js:12:990633)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1045869)
    at ok (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028864)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028730
    at oG (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028738)
    at oD (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1025823)
    at r5 (https://discord.com/assets/web.afed570d83e54e09da87.js:12:974497)
    at ob (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1026327)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054414
    at ll (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054444)
    at t.render (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by flamedance58** [comment] 2024-08-15 22:56
This is what I'm getting.

```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576698
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523341)
    at c (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523728)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576672)
    at p (https://discord.com/assets/958ef280f246c8d801de.js:1:5901)
    at aA (https://discord.com/assets/web.afed570d83e54e09da87.js:12:990633)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1045869)
    at ok (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028864)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028730
    at oG (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028738)
    at oD (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1025823)
    at r5 (https://discord.com/assets/web.afed570d83e54e09da87.js:12:974497)
    at ob (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1026327)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054414
    at ll (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054444)
    at t.render (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

**Comment by Andy76swe** [comment] 2024-08-15 23:12
yep broken here too

**Comment by DimTheEnderman** [comment] 2024-08-16 01:58
Broken for me too

**Comment by wthueb** [comment] 2024-08-16 02:16
The traceback indicates that it happens [here](https://github.com/rauenzi/BDPluginLibrary/blob/94841acc3ce3095a30a2dddb898d2735c8e06f2b/src/ui/popouts.js#L79) however I'm not familiar enough with debugging BD/React stuff to figure out what exactly the issue is.

**Comment by ashergz** [comment] 2024-08-16 04:02
It's dead, Jim!

**Comment by MatthewH12** [comment] 2024-08-16 04:09
This MAY or MAY NOT work, it's a bit of a hack, but change the line in 0PluginLibrary.plugin.js from:
        ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer);
by adding a // in front, like so:
//        ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer);

This will comment out that line.

**Comment by DoYouKnowMyNamePlz** [comment] 2024-08-16 07:23
Yay another thing broken and devs not at least letting people know they are aware of the issue so it gets spammed tf out of.

**Comment by thc282** [comment] 2024-08-16 10:48
same is participants error
```
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576698
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523341)
    at c (https://discord.com/assets/web.afed570d83e54e09da87.js:12:9523728)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:5576672)
    at p (https://discord.com/assets/958ef280f246c8d801de.js:1:5901)
    at aA (https://discord.com/assets/web.afed570d83e54e09da87.js:12:990633)
    at l (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1045869)
    at ok (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028864)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028730
    at oG (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1028738)
    at oD (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1025823)
    at r5 (https://discord.com/assets/web.afed570d83e54e09da87.js:12:974497)
    at ob (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1026327)
    at https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054414
    at ll (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1054444)
    at t.render (https://discord.com/assets/web.afed570d83e54e09da87.js:12:1058139)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
  ```

**Comment by ManchiSoul** [comment] 2024-08-16 14:57
> This MAY or MAY NOT work, it's a bit of a hack, but change the line in 0PluginLibrary.plugin.js from: ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer); by adding a // in front, like so: // ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer); This will comment out that line, and seems to let it load now, but is probably still broken in other ways.

worked well for me ty !!

**Comment by Katashtrophic** [comment] 2024-08-16 15:31
still having issue even after popup on starting saying fixed

**Comment by dustin-lennon** [comment] 2024-08-16 16:07
I was doing a little research myself by building the library with some console logs and am finding that the container and the layer container are both empty objects. I don't know what would trigger data to be in those objects. That explains why this error is occurring `Cannot read properties of undefined (reading 'participants')`.

**Comment by ScottishMonk** [comment] 2024-08-16 16:11
did discord remove somethings that's not reading properties?

**Comment by cxosa** [comment] 2024-08-16 17:01
@MatthewH12 IS A GOAT, YO?!??! 

> ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer);
> by adding a // in front, like so:
> // ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer);

this js worked

**Comment by dustin-lennon** [comment] 2024-08-16 17:27
> did discord remove somethings that's not reading properties?

This is ALWAYS a possibility

**Comment by Zhurama** [comment] 2024-08-16 19:38
@MatthewH12 
#232 

This definitely helped. The plugin cursorily loads, but is still throwing in app errors.. It's better, and at least the error remarks no longer fill the entire screen.

**Comment by dustin-lennon** [comment] 2024-08-16 22:19
> @MatthewH12
> 
> This MAY or MAY NOT work, it's a bit of a hack, but change the line in 0PluginLibrary.plugin.js from: ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer); by adding a // in front, like so: // ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer); This will comment out that line, and seems to let it load now, but is probably still broken in other ways.**
> 
> This definitely helped. The plugin cursorily loads, but is still throwing in app errors.. It's better, and at least the error remarks no longer fill the entire screen.

It works because you are no longer rendering the element.

**Comment by Andy76swe** [comment] 2024-08-16 23:47
what other plugins uses this crap?

**Comment by B-Nerd** [comment] 2024-08-17 00:21
> what other plugins uses this crap?

i think everything made by Zerebos

**Comment by ScottishMonk** [comment] 2024-08-17 06:17
huh so funny thing there was an update but its still broken for me

**Comment by KlasycznaReimu** [comment] 2024-08-17 09:38
have same issue today

**Comment by fowlis** [comment] 2024-08-17 10:15
Any "same" or "i have the same issue" comments are unhelpful and just clog up the thread. Either provide useful information about the issue or say nothing. Zere will fix this when he wants to.

Just be patient.

**Comment by NathanTheGraves** [comment] 2024-08-17 22:28
TBH, of all the plugins that got screwed by the Discord changes, it was only Zeres' one for me, and from that the only plugin that seems to really use it, is AppNotifications, so nothing important really.

This will get updated when it's done, like it has been in the past. I can just imagine how annoying it must be to have to verify what changed in order to update it and then worry about the next update just breaking everything again, so I can understand why one would take their time updating.

**Comment by D3nschot** [comment] 2024-08-18 01:48
I was messing around with the code it maybe caused by Popouts.initialize() something must be wrong with the Popups _(or popouts idk)_ or its assets missing but I'm not really sure becuase of my very little research by searching _what is Pop outs in js_  it gave me the definition of a popups in js
again idk I'm just an idiot that likes to mess around with code

**Comment by ScottishMonk** [comment] 2024-08-18 09:58
mind you thats mainly for the bdcontextmenu or am i wrong?

**Comment by Lusiiky** [comment] 2024-08-18 12:10
Same: ´Plugin constructor() failed to return.´
´´´
TypeError: Cannot read properties of undefined (reading 'participants')
    at https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:5577611
    at l (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:9526588)
    at c (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:9526975)
    at l (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:5577585)
    at p (https://ptb.discord.com/assets/76691fb613307173f03a.js:1:5958)
    at aA (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:990088)
    at l (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1045324)
    at ok (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1028319)
    at https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1028185
    at oG (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1028193)
    at oD (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1025278)
    at r5 (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:973952)
    at ob (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1025782)
    at https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1053869
    at ll (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1053899)
    at t.render (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1057594)
    at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
    at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
´´´

Thank you!

**Comment by ScottishMonk** [comment] 2024-08-18 12:27
> Same: `Plugin constructor() failed to return.`
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'participants')
>     at https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:5577611
>     at l (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:9526588)
>     at c (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:9526975)
>     at l (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:5577585)
>     at p (https://ptb.discord.com/assets/76691fb613307173f03a.js:1:5958)
>     at aA (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:990088)
>     at l (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1045324)
>     at ok (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1028319)
>     at https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1028185
>     at oG (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1028193)
>     at oD (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1025278)
>     at r5 (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:973952)
>     at ob (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1025782)
>     at https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1053869
>     at ll (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1053899)
>     at t.render (https://ptb.discord.com/assets/web.db54393173846a7259b2.js:12:1057594)
>     at Popouts.initialize (betterdiscord://plugins/0PluginLibrary.plugin.js:4512:18)
>     at new PluginLibrary (betterdiscord://plugins/0PluginLibrary.plugin.js:6146:49)
>     at N.initializeAddon (betterdiscord/renderer.js:5:27014)
>     at N.loadAddon (betterdiscord/renderer.js:5:6406)
>     at N.loadAddon (betterdiscord/renderer.js:5:26269)
>     at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
>     at N.initialize (betterdiscord/renderer.js:5:3093)
>     at N.initialize (betterdiscord/renderer.js:5:25382)
>     at Object.startup (betterdiscord/renderer.js:5:408589)
> ```
> 
> Thank you!

sorry but did you read the post this does not help at all

**Comment by Lusiiky** [comment] 2024-08-18 13:13
@ScottishMonk 
> sorry but did you read the post this does not help at all

Sorry.. I don't really understand everything in the post so.. I just wanted to tell that i've the same (I think) problem..

**Comment by ScottishMonk** [comment] 2024-08-18 13:15
> @ScottishMonk
> 
> > sorry but did you read the post this does not help at all
> 
> Sorry.. I don't really understand everything in the post so.. I just wanted to tell that i've the same (I think) problem..

yea no you got the same problem dont worry it will get fixed

**Comment by rotund-sloth** [comment] 2024-08-18 15:18
![image](https://github.com/user-attachments/assets/948835ec-bd4e-49f6-a4ed-dd44032657d4)

**Comment by rampso** [comment] 2024-08-18 20:06
https://github.com/1Lighty/BetterDiscordPlugins/blob/master/Plugins/1XenoLib.plugin.js

is fixed here. mine isnt auto downloading it but this fix worked by replacing the file

**Comment by ImGGAAVVIINN** [comment] 2024-08-19 00:28
> it will get fixed

Yeah, we know, since this project is not discontinued. But not stating **when** it will get fixed is not very productive here. From a use perspective, getting an error every time you open discord is not a great user experience.

**Comment by tenjinz-github** [comment] 2024-08-20 01:56
> > it will get fixed
> 
> Yeah, we know, since this project is not discontinued. But not stating **WHEN** it will get fixed is not very productive here. From a user perspective, getting an error every time you open discord is not a great user experience.

Like the other guy said, when dealing with free work like this, you get it when you get it. No one has an obligation to fix this, it could stay broken forever if they want it to. It was free, it's being done on their free time, and if they're a one man team, it could take a lot of time to figure out what's broken and fix. 

If you're not going to fix it yourself, then don't complain, just wait, or stop using it if you don't like the service you're getting...for free.

**Comment by ImGGAAVVIINN** [comment] 2024-08-20 03:11
> > > it will get fixed
> > 
> > 
> > Yeah, we know, since this project is not discontinued. But not stating **WHEN** it will get fixed is not very productive here. From a user perspective, getting an error every time you open discord is not a great user experience.
> 
> None of us know when it will get fixed. Complaining about slow customer service when dealing with open source software is nonsensical. Just be patient and it will get fixed. That, or. Y'know. It's open source. You can always open a PR.

Sorry about that

**Comment by plaxorizor** [comment] 2024-08-20 16:56
While we wait for the fix, I temporarily remove the code at line 6144 just to get my plugins proceed. I only use few plugins, so this works for me.

https://github.com/rauenzi/BDPluginLibrary/blob/94841acc3ce3095a30a2dddb898d2735c8e06f2b/release/0PluginLibrary.plugin.js#L6144

**Comment by Scorpions95** [comment] 2024-08-20 18:43
When this issue will be fixed?

**Comment by B-Nerd** [comment] 2024-08-20 18:45
> When this issue will be fixed?

when it is fixed it is open source so mostly a side project so when they have time

**Comment by B-Nerd** [comment] 2024-08-20 18:48
side project

Vriendelijke Groet Benjamin van Ark

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by B-Nerd** [comment] 2024-08-20 18:50
> > > When this issue will be fixed?
> > 
> > 
> > when it is fixed it is open source so mostly a side project so when they have time
> 
> but, it's so much people post same issue, think have to fix this

try to change this line
ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer);
& make it this
// ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer);

**Comment by theapathyimp** [comment] 2024-08-20 23:07
this isn't the forum so i'll keep it brief, but some of y'all really need to question your motivations for whinging about it not being fixed when you couldn't do the work, much less for free or in the amount of time the dev can/does. zeres is a pillar of betterdiscord development and he(?) has a life outside of making your discord client slightly less shitty.

react is a very advanced language, for that matter, and that's not even accounting for the fact that plugin devs have to spend countless hours reverse engineering whatever nonsense bullshit discord decided to do this week to get things working again.

have a little grace and patience, i mean come on.

that being said, having reviewed the error and _productive_ comments in the thread, i agree it has something to do with those popouts, most likely whatever this block calls got deleted in the base client.
`static initialize() {
        // return;
        this.dispose();
        this.popouts = 0;

        this.container = Object.assign(document.createElement("div"), {
            className: "ZeresPluginLibraryPopoutsRenderer",
            style: "display: none;"
        });

        this.layerContainer = Object.assign(document.createElement("div"), {
            id: "ZeresPluginLibraryPopouts",
            className: modules__WEBPACK_IMPORTED_MODULE_0__.DiscordClassModules.TooltipLayers.layerContainer
        });

        document.body.append(this.container, this.layerContainer);
        //ReactDOM.render(React.createElement(PopoutsContainer), this.layerContainer); ***commented this out per advice earlier in thread, it is _not_ commented in current source***
    }`

i'm not a developer, and especially not a react dev, so i can only theorize here, but hopefully it's helpful to bug fixing when the time comes that we've (potentially) narrowed it down some,

**Comment by rauenzi** [comment] 2024-08-21 15:42
For now the popouts module has been disabled since it is seldom-used anyways and has been broken for a long time. This is fixed in the latest version, it will be a bit before it approved on the BD website.

**Closed by rauenzi** 2024-08-21 15:42 UTC

**Comment by corpsiesan** [comment] 2024-08-21 17:22
how do i fix this error? im not good at programs and stuff

**Comment by B-Nerd** [comment] 2024-08-21 22:40
> how do i fix this error? im not good at programs and stuff

it is fixed

**Comment by ImGGAAVVIINN** [comment] 2024-08-27 09:53
> For now the popouts module has been disabled since it is seldom-used anyways and has been broken for a long time. This is fixed in the latest version, it will be a bit before it approved on the BD website.

Thank your sir :D
